### ISSUE TITLE
Обновления API

### ISSUE THREAD

**Issue by RichardFerlow** [DrTeamRocks/uon#1]
Привет.
В ходе переписки с техподдержкой, они добавили еще один метод
https://api.u-on.ru/{key}/request/update/{id}.{_format} - правда доступно только указание покупателя по id =)

**Comment by EvilFreelancer** [comment]
@RichardFerlow благодарю за уточнение :smile: как появится время добавлю.

**Comment by EvilFreelancer** [comment]
@RichardFerlow добавил метод update($id_client, $prarams) в класс Request и доку тоже обновил. Можно пробовать.

**Comment by ivanskins** [comment]
Тут указывается ID заявки, метод ведь обновляет именно заявку, по ее ID

**Comment by RichardFerlow** [comment]
Да, перепутал немного =)

**Comment by EvilFreelancer** [comment]
ок, поменял
