### ISSUE TITLE
endpoint для постраничного поиска обращений

### ISSUE THREAD

**Issue by azagoru** [DrTeamRocks/uon#10]
В Leads.php 65 строчка
$endpoint = '/lead/' . $date_from . '/' . $date_to;
Согласно документации для постраничного поиска должно быть
$endpoint = '/leads/' . $date_from . '/' . $date_to;
Иначе возвращает некорректное количество результатов, а в случае, когда указан $source_id, возвращает false.

<img width="1433" alt="screenshot 2019-02-07 at 10 48 32" src="https://user-images.githubusercontent.com/20268138/52397301-f5aa1880-2ac5-11e9-9292-bfe3621f19bd.png">

**Comment by EvilFreelancer** [comment]
Добрый день! Добавлю сегодя.

**Comment by EvilFreelancer** [comment]
Исправил опечатку в коде, заодно обновил документацию, добавил экспешенов, немного отрефакторил локигу создания объекта API и удалил устаревшие кусочку.
Можно обновиться до 1.9 там всё будет.
