### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by RichardFerlow** [DrTeamRocks/uon#11]
Почему-то use UON\Endpoint\Services; в API.php нет. так и надо?

**Comment by EvilFreelancer** [comment]
Добрый день!
По идее должен быть, но я мог и забыть его указать, Вы можете добавить фикс самостоятельно и создать Pull Request, это дело пары минут :)

**Comment by RichardFerlow** [comment]
Я просто пока еще не сильно близок к всему такому))))

**Comment by EvilFreelancer** [comment]
@RichardFerlow добавил фикс в 1.9.1, обновляйся и чекай ;) но если будет время рекомендую разобраться в том как делать Pull Request, на самом деле это очень просто и нужные правки смогу выкладывать намного быстрее.
