### ISSUE TITLE
doRequest всегда возвращает status false

### ISSUE THREAD

**Issue by FuckoffGroup** [DrTeamRocks/uon#3]
Доброго времени суток, в методе doRequest класса Client написано следующее
`return array('status' => false, 'message' => json_decode($result->getBody()));`
Думаю, что ,при удачном выполнении операции,  должно возвращаться true :))

**Comment by EvilFreelancer** [comment]
@FuckoffGroup отличное замечание, благодарю.

По всей видимости данный недочёт остался после упрощения клиента-прослойки, в версии 1.8 данная ошибка будет исправлена (а так же будет много других изменений).
