### ISSUE TITLE
Метод request-document

### ISSUE THREAD

**Issue by FuckoffGroup** [DrTeamRocks/uon#4]
Еще замечание на будущее :)
Данный метод возвращает pdf/doc файл, а не json.

**Comment by EvilFreelancer** [comment]
Интересно, я думал должен быть JSON с base64 данными внутри, забавное решение.

**Comment by EvilFreelancer** [comment]
@FuckoffGroup поправил эту ошибку, ну и много чего ещё добавил, смотрите в релизе 1.8
