### ISSUE TITLE
Задержка....

### ISSUE THREAD

**Issue by RichardFerlow** [DrTeamRocks/uon#5]
Нельзя ли как-то придумать глобальное ограничение не более 5 запросов в секунду? Это в свете новых ограничений.
Сам пока не знаю как это сделать, в рамках одного скрипта там банально после 5 запросов паузу можно делать, а если скрипты разные, то только очень сложные варианты в голову приходят,

**Comment by EvilFreelancer** [comment]
Вероятно надо будет изобретать какую-нибудь очередь специально для этого, ума не приложу что мешает разработчикам просто со стороны сервера настроить время отклика.

---

Могу как временное решение предложить добавить таймаут в ваш скрипт (там где тригерится реквест), думаю одной или полсекунды будет достаточно.

**Comment by RichardFerlow** [comment]
Типа если сработал ответ - превышено кол-во запросов, то паузу запускать?

**Comment by ilyabakhlin** [comment]
Проблема с задержкой следующая: каждый PHP запрос независим от других запросов, т. е. в данном языке программирования нет возможности делится параметрами или переменными.

Эту проблему можно решить двумя способами:

1. Разработчики фирм, которые работают с API U-On, должны поставить систему сообщений, типа RabbitMQ, или делится информацией между PHP запросов при помощи базы данных, Memcached, Redis или даже файлами.
2. Написать данную систему сообщений нам самим и позволить разработчикам делать запросы туда.

**Comment by RichardFerlow** [comment]
UON предлагают следующее:

ставите while цикл и отслеживаете:
1) ответ 200, выход из цикла
2) ответ 405, запрос через секунду

Сижу думаю...это надо столько условий учесть, чтобы в бесконечный цикл это все не ушло...

**Comment by ilyabakhlin** [comment]
Блядь... А ничего более умного они не могли посоветовать?

С другой стороны проблему можно решить ещё и рекурсией:

```php
function getSomething() {
    if ($doSomething->getResponseCode() === 200) {
        return $doSomething->getResponse();
    } else {
        sleep 1;
    }
    return getSomething();
}
```

**Comment by ilyabakhlin** [comment]
Ещё идея есть написать модуль который кашировал все данные которые приходят с сервера U-On.

**Comment by RichardFerlow** [comment]
Я итак кэширую, только это для статичных данных помогает же.

В рекурсии выше по-моему если ответ 200 будет, то два раза return будет, а если не 200, а ответа нет или проблемы связи-сервера - цикл замкнется

**Comment by ilyabakhlin** [comment]
Согласен. Единственный способ решить эту проблему, который я могу придумать на данный момент, это дублировать сервис API.

@EvilFreelancer, что ты думаешь об этой проблеме?

**Comment by RichardFerlow** [comment]
Дублировать - типа раз в сутки весь контент выкачивать, и уже с ним работать?

**Comment by ilyabakhlin** [comment]
Я думаю что да. Больше идей у меня нет.

**Comment by EvilFreelancer** [comment]
@ilyabakhlin хм, очень интересная, но врятли осуществимая идея, типа делать статическую версию данных? Как по мне слишком много чего может меняться в один момент времени, например если часто путёвки добавляться, поэтому их кэшировать плохая идея, а вот для статики всякой, вроде типов туров, должно быть отлично.
@RichardFerlow насчёт кода 405 могу добавить проверку, HTTP клиент будет считывать код ответа сервера и если 405 тогда повторять через секунду, одако, как уже было выше замеченно это может привести к бесконечному циклу (или к нескольким зависшим циклам), но если делать проверку на количество повторов допустим 10 максимум, то всё должно быть ок (ну если не обращать внимание на то что что это костыль).

**Comment by RichardFerlow** [comment]
Вот я тоже про цикл бесконечный подумал как проблему, но еще не пришел к пониманию как точно бы все сделать это. Если бы вы могли это реализовать - был бы очень благодарен.

**Comment by RichardFerlow** [comment]
Вес контент кэшировать у себя крайне накладно и сложно. У нас допустим только клиентов больше 40тыс в базе, а есть еще обращения и заявки и кучи справочников. Несколько часов все это будет копироваться ежедневно, и актуальность будет суточной давности, поэтому такой способ лично для нас только как бэкапирование подходит

**Comment by EvilFreelancer** [comment]
@RichardFerlow через пару часов запушу апдейт по этому поводу, ждите новостей :)

**Comment by RichardFerlow** [comment]
Ждем =)

**Comment by RichardFerlow** [comment]
Я забыл, а у версии 1.8 и новее какая обратная совместимость с предыдущими версиями? переписывать всё придется?)

**Comment by ilyabakhlin** [comment]
Все изменения указаны [здесь](https://github.com/DrTeamRocks/uon/releases/tag/1.8).

**Comment by RichardFerlow** [comment]
Там указано 

"Major version is changed, that mean - your existed code may be not compatible with this release, please read documentation to lean what changed"

про обратную совместимость это не дает понять мне.

**Comment by EvilFreelancer** [comment]
@RichardFerlow namespace эндпоинтов был изменён на `\Endpoint\` то есть Вам нужно просто добавить префикс в Ваши классы. Однако, я добавил более удобный метод работы с классами на базе концеции Dependency Injection (и magic методов), через API класс.

Раньше (до 1.8) было как:
```php
// Создать объект для работы endpoint'ом
$users = new \UON\Users('UON_TOKEN');
// или так 
// $config = new Config() // здесь можно через `set` метод указать параметры для HTTP клиента
// $config->set('token', 'your-uon-token');
// $users = new \UON\Users($config);
// Тригернуть нужный метод
$users->get(1);
```
Теперь (с 1.8) должно быть так:
```php
$config = new Config() // здесь можно через `set` метод указать параметры для HTTP клиента
$config->set('token', 'your-uon-token');
// Потом нужно создать объект для работы с API
$api = new API($config);
// Тригернуть нужный метод
$api->users->get(1);
```
Но для обратной совместимости можно сделать так:
```php
$config = new Config() // здесь можно через `set` метод указать параметры для HTTP клиента
$config->set('token', 'your-uon-token');
// Создать объект для работы endpoint'ом
$users = new \UON\Endpoint\Users($config);
// Тригернуть нужный метод
$users->get(1);
```

---

Залил обновление клиента, добавил проверку на 429 ошибку, сейчас погоняю тесты и если всё ок выпускаю в релиз.

**Comment by EvilFreelancer** [comment]
Релиз 1.8.1 уже доступен для загрузки через composer, всех заинтересованных в решении ошибки 429 прошу обновить библиотеку и проверить что всё работает так как нужно.

@RichardFerlow насчёт обратной совместимости (а точнее миграции с 1.7) я вроде пояснил выше, но если возникнут сложности или что-то непонятно, то создайте новый тикет и опишите проблему с экземпляром кода (без токена конечно же :) постараюсь помочь.
