### ISSUE TITLE
Можно ли провести сравнение и добавить недостающие методы?

### ISSUE THREAD

**Issue by RichardFerlow** [DrTeamRocks/uon#7]
Знаю что за обновлениями в API следить сложно, но там часто что-то обновляют, добавляют, допустим https://api.u-on.ru/{key}/lead/search.{_format} какое-то время назад уже появился, в библиотеке его нет еще, думаю вероятно еще что-то найдется. Я могу составить список если нужно.

По совместимости обратной, стоит добавить что раньше возвращало status , теперь code
Не страшно, просто переделать пришлось.

Так обновился на 1.8.1 - полет нормальный, спасибо.

**Comment by RichardFerlow** [comment]
По совместимости обратной, стоит добавить что раньше возвращало status , теперь code 
Не страшно, просто переделать пришлось.

**Comment by EvilFreelancer** [comment]
Как-то так https://github.com/DrTeamRocks/uon/wiki/Миграция-с-1.7-(и-ниже)-на-1.8-(и-выше), если что-то забыл можешь подправить, wiki публичная и открыта для всех.

**Comment by EvilFreelancer** [comment]
Версия 1.8.2 доступна для скачивания.
