### ISSUE TITLE
Не останавливаются попытки при получении ошибки 500

### ISSUE THREAD

**Issue by RichardFerlow** [DrTeamRocks/uon#8]
Вчера что-то навернулось и на lead create UON стал выдавать {"error":{"code":500,"message":"Internal Server Error"}}. обращение при этом создётся.

Но скрипт делает свои 10 попыток, таким образом создаются 10 обращений.

Ну и такой момент что пытаюсь посмотреть "что там", смотрю

$request = $_leads->create($params);
print_r($request);

но $request пустой

**Comment by EvilFreelancer** [comment]
Вот это забаная тема, похоже что-то в API в очередной раз сломали ;) добалю дополнительную проверку 500й ошибки.

**Comment by EvilFreelancer** [comment]
@RichardFerlow чекай релиз 1.8.3

**Comment by RichardFerlow** [comment]
Благодарю!
