### ISSUE TITLE
Ошибка в getReasonDeny

### ISSUE THREAD

**Issue by RichardFerlow** [DrTeamRocks/uon#9]
$endpoint = '/company-office'; 

а должно быть $endpoint = '/reason_deny';

Еще в suppliers ->all(array $parameters = [], $page = 1) для чего-то идет массив параметров, а судя по докам там только номер страницы передать можно.

**Comment by EvilFreelancer** [comment]
Интересный баг, похоже документация обновилась, надеюсь коллеги из UON когда-нибудь додумаются до Swagger, чтобы можно было в полуавтоматическом режиме клиента обновлять.

**Comment by EvilFreelancer** [comment]
@RichardFerlow ошибка исправлена в релизе 1.8.4
